# Copyright 2026 Christopher R. Vessell. Licensed under the Apache License, Version 2.0. See LICENSE.
"""Importable VessellFramework core package.

Public surface: evidence intake and provenance tracking plus the
provenance-tagged claim lifecycle — intake, corroboration, gating,
disavowal, and correction propagation (:mod:`vessell.provenance`),
deterministic + LLM-calibrated evidence weighting (:mod:`vessell.weights`),
the calibrated live-Llama weighter (:mod:`vessell.weighter`), and claim
verification — planted-news checks, hostile-spread intel, and ghost-job
filtering (:mod:`vessell.verify`), and the claim x source verification
matrix (:mod:`vessell.report`) with its heat map renderer
(:mod:`vessell.heatmap`, CLI ``vf-heatmap``), and the attack-surface
heat map over open-source scanner output (:mod:`vessell.attack_surface`,
CLI ``vf-attack-surface``).
"""

from vessell.malware_triage import triage_source_and_record
from vessell.provenance import (
    CausalOrderingError,
    ClaimEvent,
    ClaimGateBlocked,
    ClaimKind,
    ClaimRecord,
    ClaimStatus,
    ClaimWaiver,
    Corroboration,
    Dependent,
    DependentStatus,
    Disavowal,
    EvidenceItem,
    EvidenceSet,
    ProvenanceRegistry,
    ProvenanceResolution,
    ProvenanceState,
    SourceStatus,
    add_corroboration,
    claim_events,
    confirm_dependent_update,
    deliver_correction,
    disavow,
    gate_for_use,
    get_claim,
    intake_claim,
    pending_corrections,
    propagate_correction,
    record_event,
    record_waiver,
    register_dependent,
    require_gate,
    reset_claim_lifecycle,
    revalidate_claim,
    verify_event_chain,
)
from vessell.report import event_matrix
from vessell.validation import require_provenance_fields
from vessell.verify import (
    BURST_MIN_SOURCES,
    BURST_WINDOW_MINUTES,
    CLONE_ARMY_MIN_SOURCES,
    MIN_ABSENCE_PATHS,
    NEAR_DUPLICATE_THRESHOLD,
    ClaimCheck,
    GhostJobReport,
    GhostVerdict,
    JobPosting,
    PlantedNewsReport,
    PlantedVerdict,
    SearchPath,
    SourceSighting,
    Verdict,
    VerificationResult,
    analyze_planted_news,
    analyze_planted_news_and_record,
    clock_sort_key,
    detect_clock_drift,
    detect_ghost_job,
    detect_ghost_job_and_record,
    filter_ghost_jobs,
    gate_negative_finding,
    group_postings_by_role,
    record_search_path,
    require_negative_finding,
    reset_search_paths,
    search_paths,
    verify_and_record,
    verify_claim,
)
from vessell.weighter import (
    CalibratedLlamaWeighter,
    LlamaDetailedScore,
    combine_factors,
)
from vessell.weights import (
    SOURCE_TIER_WEIGHTS,
    WEIGHT_TABLE_VERSION,
    AggregationResult,
    LlamaScore,
    LlamaUnavailable,
    LlamaWeighter,
    WeightedEvidenceSet,
    WeightingEngine,
    WeightRecord,
)

__version__ = "3.9.1"

__all__ = [
    "BURST_MIN_SOURCES",
    "BURST_WINDOW_MINUTES",
    "CLONE_ARMY_MIN_SOURCES",
    "MIN_ABSENCE_PATHS",
    "NEAR_DUPLICATE_THRESHOLD",
    "SOURCE_TIER_WEIGHTS",
    "WEIGHT_TABLE_VERSION",
    "AggregationResult",
    "CalibratedLlamaWeighter",
    "CausalOrderingError",
    "ClaimCheck",
    "ClaimEvent",
    "ClaimGateBlocked",
    "ClaimKind",
    "ClaimRecord",
    "ClaimStatus",
    "ClaimWaiver",
    "Corroboration",
    "Dependent",
    "DependentStatus",
    "Disavowal",
    "EvidenceItem",
    "EvidenceSet",
    "GhostJobReport",
    "GhostVerdict",
    "JobPosting",
    "LlamaDetailedScore",
    "LlamaScore",
    "LlamaUnavailable",
    "LlamaWeighter",
    "PlantedNewsReport",
    "PlantedVerdict",
    "ProvenanceRegistry",
    "ProvenanceResolution",
    "ProvenanceState",
    "SearchPath",
    "SourceSighting",
    "SourceStatus",
    "Verdict",
    "VerificationResult",
    "WeightRecord",
    "WeightedEvidenceSet",
    "WeightingEngine",
    "__version__",
    "add_corroboration",
    "analyze_planted_news",
    "analyze_planted_news_and_record",
    "claim_events",
    "clock_sort_key",
    "combine_factors",
    "confirm_dependent_update",
    "deliver_correction",
    "detect_clock_drift",
    "detect_ghost_job",
    "detect_ghost_job_and_record",
    "disavow",
    "event_matrix",
    "filter_ghost_jobs",
    "gate_for_use",
    "gate_negative_finding",
    "get_claim",
    "group_postings_by_role",
    "intake_claim",
    "pending_corrections",
    "propagate_correction",
    "record_event",
    "record_search_path",
    "record_waiver",
    "register_dependent",
    "require_gate",
    "require_negative_finding",
    "require_provenance_fields",
    "reset_claim_lifecycle",
    "reset_search_paths",
    "revalidate_claim",
    "search_paths",
    "triage_source_and_record",
    "verify_and_record",
    "verify_claim",
    "verify_event_chain",
]
